### ISSUE TITLE
OOM when run

### ISSUE THREAD

**Issue by Janspiry** [xindubawukong/LQ-Nets_Pytorch#1]
Hi, thanks for this awesome work!

I used it in detection task with the ResNet50 backbone, but get the CUDA Error: out of memory.
Can you tell me the memory usage when you run it? I suspect there is room for optimization in this section in the pytorch version.

Looking forward to your reply, and thanks again!

**Comment by xindubawukong** [comment]
hi @Janspiry.
Sorry to tell you that I've forgot the details of this project.

**Comment by Janspiry** [comment]
Thanks for answer.
